### ISSUE TITLE
COwr_S14397 site tagged as high volume, but landing page it was 0 volume.

### ISSUE THREAD

**Issue by rwjam** [WSWCWaterDataExchange/WestDAAT#203]
This site in CO (COwr_S14397, water right 11438.0-0-C-303400) was tagged with a volume, but the volume on the landing page was 0.  Follow up on this.

- Is the CFS and Volume both 0 from the source data?
- Is the maptiler out of date?

![image](https://user-images.githubusercontent.com/17555073/217960657-5e0d4f1d-0183-417b-bd67-5b0fed8d4410.png)

**Comment by amabdallah** [comment]
In future bugs, let's report the URL for the WestDAAT landing page to help reproduce the error later. 

Not sure if the data was updated after this issue was reported, but the water right doesn't seem to exist 

https://westdaatstaging.westernstateswater.org/details/right/COwr_S14397?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABhNSSwFcAJshgAWDgDoOANikAOfGI5KlAVm40AdgHN%2BQmNk5TxsgMyy2c5crYB2AL52gA
