### ISSUE TITLE
Add additional metadata items to the Water right Information card on the water right landing page

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#255]
We need to add the following additional metadata items to the Water right Information card on the water right landing page. These metadata features already exist in the WaDE database in the Core_AllocationAmounts_fact table

Let's have all of them next to each other on the Card (below the WaDE Irrigation Method)
Label to use on the Landing Page | Metadata field name in the database
-- | --
Irrigated   Acreage | IrrigatedAcreage
Crop Type | CropTypeCV
Irrigation   Method | IrrigationMethodCV

**Comment by Rhipeus** [comment]
@amabdallah - What displays as "WaDE Irrigation Method" today is already the "IrrigationMethodCV."  I would recommend the following in order since most of the WaDEName data for the Irrigation Method WaDE Name is empty:

<html>
<body>


Label to use on the Landing Page | Metadata field name in the database
-- | --
Irrigation Method | IrrigationMethodCV
Irrigated Acreage | IrrigatedAcreage
Crop Type | CropTypeCV
WaDE Irrigation Method | CVs.IrrigationMethod.WaDEName


</body>
</html>

Does that work?
