### ISSUE TITLE
Display one label per POU

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WestDAAT#77]
Why do we have multiple identical labels showing up for the POU polygon here? I was confused thinking there are multiple ones (hiding below) until I realized they are the same label

link to recreate: https://westdaat.westernstateswater.org/details/site/WAwr_S160080?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YAOAOgGYB2ABgBMbLlwAsAkaP4CSqJFgCuAE2QwpHIfh7CuAgKwBGbTx6jZNAHYBzRSpjYDAvh3wDtY-FwBsX13vwAvgFAA

![image](https://user-images.githubusercontent.com/3268971/162063786-62192b72-01fa-4173-9b49-5bdc40a57006.png)

**Comment by amabdallah** [comment]
https://westdaatqa.westernstateswater.org/details/right/3048799

**Comment by Rhipeus** [comment]
The issue here is that the geometry is a multi-polygon (multiple individual polygons are used to define the region).  Mapbox is adding a label for each polygon in that multi-polygon.  There may be a way to reduce some of this.  Some of the multi-polygons could be simplified/combined to only be a single polygon.  This could be done in the spreadsheet loading the data or the import could probably be updated to do the simplification itself.

However, that won't solve all of the problems, including your example.  When the geometry has multiple non-contiguous regions, it will require a multi-polygon and multiple labels.  You need those labels if there is a moderate distance between the sections or if there are multiple POUs.  I am unaware of a way to make Mapbox behave the way you are requesting and it may be a bad idea.

**Comment by amabdallah** [comment]
Thanks, Nathan. Good to know. 
Here is a better example of a canal company with a ton of irrigated fields. They're separate, so we can't do much about them. 
https://westdaatstaging.westernstateswater.org/details/right/UTwr_WR57219?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGAVgDo38AODnwDMABg5CAbCJH5JJVEiwBXACbIYAFhFchGvn3waATBvwnZfeTQB2Ac2VqY2Nm20ah%2BfBwlshvIwDsEhIAviFAA

**Comment by amabdallah** [comment]
We want to avoid joining the polygons but I think the pop-up card now gives users what they want. The label was intended to let the user know which site is on the list. So I think we could remove the labels now. @rwjam what do you think?

We need to review the entire layout of the landing page and removing the label could be part of that task.
Example
https://westdaatstaging.westernstateswater.org/details/right/UTwr_WR711572?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YAWAOgAYeAmfNgGZBAdl6D8XESVRIsAVwAmydlw4BGfADYAHFt4BWfLy5tNvNjJoA7AOYLlMbOq74Ok0YJ0WDbLut4AX0CgA

**Comment by amabdallah** [comment]
Here is a good example (removing the labels)
https://westdaat.westernstateswater.org/details/right/NEwr_WR7981?state=N4IgtgziBcIQhgFwKYBtUEsUFoBuBOEAGnHgAcZQAvAexrABllc0YBGABgDoA2AFgAcAdnwBmDgCYeHHgFZ8JVEiwBXACbIYfCV1lCBPCfgni%2Bs2W36KaAOwDmqjTGz58XIUMECJRqQNH4PAC%2BQUA

**Comment by amabdallah** [comment]
The issue is refocused now here
https://github.com/WSWCWaterDataExchange/WestDAAT/issues/295
